export const CATEGORY_DROPDOWN_ITEMS: Record<string, Record<string, string[]>> = {
  "cat-safety-shoes": {
    "Steel Toe Shoes": [
      "Liberty Warrior 101",
      "Hillson Beston Pro",
      "Karam Quipo Steel Toe",
      "Allen Cooper AC-1001",
      "Bata Industrials Endura",
    ],
    "PU Sole Shoes": [
      "Karam Quipo PU Sole",
      "Hillson Nucleus PU",
      "Liberty Warrior PU 202",
      "Fausto Milan PU",
      "Acme Storm PU Sole",
    ],
    "Double Density": [
      "Liberty Combat DD",
      "Hillson Titan Double Density",
      "Karam FS-62 DD",
      "Digger Double Density Pro",
      "Tiger Lorex DD",
    ],
    Gumboots: [
      "Mallmoon PVC Steel Toe Gumboot",
      "Acme Alpha Gumboot",
      "Liberty SBB 202 Gumboot",
      "Neosafe Industrial Gumboot",
      "Hunter Safety Gumboot",
    ],
    "Composite Toe Shoes": [
      "Karam Composite Toe CT-01",
      "Liberty Composite Safety Shoe",
      "Hillson Lite Composite Toe",
      "Allen Cooper Composite Pro",
      "Bata Composite Safety Shoe",
    ],
  },
  "cat-pvc-gumboots": {
    "Knee Length": [
      "Mallmoon 15-inch Knee Gumboot",
      "Acme Challenger Knee Boot",
      "Hunter Knee Length PVC",
      "Neosafe Knee Gumboot",
      "Liberty K-15 Knee Boot",
    ],
    "Ankle Length": [
      "Acme Ankle Gumboot AG-10",
      "Hunter Short Ankle Boot",
      "Mallmoon Ankle PVC Boot",
      "Neosafe Ankle Gumboot",
      "Liberty Ankle Safety Boot",
    ],
    "Food Grade": [
      "Food Grade White Gumboot FG-01",
      "Mallmoon FDA Approved Boot",
      "Hunter Food Processing Boot",
      "Acme Hygiene Gumboot",
      "Neosafe Food Grade Boot",
    ],
    "Chemical Resistant": [
      "Chemical Resistant CR Boot",
      "Hunter CR Acid Gumboot",
      "Mallmoon Chemical PVC Boot",
      "Acme Hazmat Gumboot",
      "Neosafe Chemical Boot",
    ],
    "Steel Toe Gumboots": [
      "Mallmoon Steel Toe PVC Gumboot",
      "Hunter Steel Toe Safety Boot",
      "Acme Steel Toe Gumboot ST-01",
      "Liberty Steel Toe PVC Boot",
      "Neosafe Steel Toe Gumboot",
    ],
  },
  "cat-reflective-jackets": {
    "Orange Mesh": [
      "Orange Mesh Jacket OM-01",
      "3M Orange Reflective Jacket",
      "Mallmoon Orange Safety Vest",
      "Karam Orange Mesh Vest",
      "Neosafe Orange Jacket",
    ],
    "Green Mesh": [
      "Green Mesh Safety Jacket",
      "Karam Green Reflective Vest",
      "Mallmoon Green Mesh Jacket",
      "3M Green Safety Vest",
      "Neosafe Green Jacket",
    ],
    Polyester: [
      "Polyester Reflective Jacket RJ-P1",
      "Karam Polyester Vest",
      "Mallmoon Poly Safety Jacket",
      "3M Polyester Reflective",
      "Allen Cooper Poly Vest",
    ],
    Cotton: [
      "Cotton Safety Jacket RJ-C1",
      "Karam Cotton Reflective Vest",
      "Mallmoon Cotton Jacket",
      "Neosafe Cotton Safety Vest",
      "Hillson Cotton Reflective",
    ],
    "Survey Jackets": [
      "Survey Reflective Jacket SR-01",
      "3M Survey Safety Vest",
      "Karam Survey Jacket Pro",
      "Mallmoon Survey Reflective Vest",
      "Neosafe Survey Jacket",
    ],
  },
  "cat-safety-helmets": {
    "HDPE Helmets": [
      "Karam PN 521 HDPE Helmet",
      "Mallmoon HDPE Safety Helmet",
      "3M HDPE Industrial Helmet",
      "Neosafe HDPE Helmet",
      "Allen Cooper HDPE Helmet",
    ],
    "Ratchet Type": [
      "Karam Ratchet Helmet PN-561",
      "3M Ratchet Adjustment Helmet",
      "Mallmoon Ratchet Helmet",
      "Neosafe Ratchet Type Helmet",
      "Venus Ratchet Helmet",
    ],
    Ventilated: [
      "Ventilated Safety Helmet VH-01",
      "Karam Ventilated Helmet",
      "3M Vent Air Helmet",
      "Mallmoon Air Flow Helmet",
      "Neosafe Ventilated Helmet",
    ],
    "With Chin Strap": [
      "Chin Strap Helmet CS-01",
      "Karam Helmet with Chin Strap",
      "3M Chin Strap Safety Helmet",
      "Mallmoon Chin Strap Helmet",
      "Venus Chin Strap Helmet",
    ],
    "ABS Helmets": [
      "Karam ABS Safety Helmet AB-01",
      "3M ABS Industrial Helmet",
      "Mallmoon ABS Helmet Pro",
      "Neosafe ABS Safety Helmet",
      "Venus ABS Helmet",
    ],
  },
  "cat-safety-gloves": {
    "Leather Gloves": [
      "Leather Driver Gloves LG-01",
      "Karam Leather Gloves",
      "Mallmoon Leather Work Glove",
      "Allen Cooper Leather Gloves",
      "Hillson Leather Driver Gloves",
    ],
    "Latex Coated": [
      "Latex Coated Grip Gloves",
      "Karam Latex Palm Gloves",
      "Mallmoon Latex Coated Gloves",
      "3M Latex Grip Gloves",
      "Neosafe Latex Coated Gloves",
    ],
    "Cut Resistant": [
      "Cut Resistant Level 5 Gloves",
      "Karam Cut Proof Gloves",
      "3M Cut Resistant Gloves",
      "Mallmoon Cut Safe Gloves",
      "Honeywell Cut Gloves",
    ],
    "Welding Gloves": [
      "Welding Heat Resistant Gloves",
      "Karam Welding Gloves",
      "Mallmoon Welding Gauntlet",
      "Allen Cooper Welding Gloves",
      "Neosafe Welding Gloves",
    ],
    "Nitrile Coated": [
      "Nitrile Coated Grip Gloves NG-01",
      "Karam Nitrile Palm Gloves",
      "3M Nitrile Coated Gloves",
      "Mallmoon Nitrile Work Gloves",
      "Honeywell Nitrile Gloves",
    ],
  },
  "cat-welding": {
    "ARC Machines": [
      "ARC 200A Welding Machine",
      "Ador Champ ARC 250",
      "Esab Buddy ARC 400",
      "Rilon ARC 200i",
      "Mallmoon ARC Welder 180A",
    ],
    "MIG Welders": [
      "MIG 250 Welding Machine",
      "Ador MIG 250",
      "Esab MIG 400i",
      "Rilon MIG 250G",
      "Miller MIG Welder",
    ],
    "Welding Rods": [
      "MS Welding Rod 3.15mm",
      "Ador Welding Electrode E6013",
      "Esab OK 46.00 Electrode",
      "Golden Bridge Welding Rod",
      "HB Welding Electrode",
    ],
    "Helmets & Gloves": [
      "Auto Darkening Welding Helmet",
      "Karam Welding Helmet",
      "3M Speedglas Helmet",
      "Mallmoon Welding Helmet",
      "Welding Glove Set",
    ],
    "TIG Welders": [
      "TIG 200A Welding Machine",
      "Ador TIG 250 Welder",
      "Esab TIG 400i",
      "Rilon TIG 200G",
      "Miller TIG Welder",
    ],
  },
  "cat-disposable-ppe": {
    "Face Masks": [
      "3 Ply Disposable Face Mask",
      "N95 Respirator Mask",
      "Surgical Face Mask Box",
      "Karam Disposable Mask",
      "Mallmoon 3 Ply Mask",
    ],
    "Shoe Covers": [
      "Disposable Shoe Cover Pack",
      "PP Shoe Cover Blue",
      "Mallmoon Shoe Cover",
      "Karam Disposable Shoe Cover",
      "Neosafe Shoe Cover",
    ],
    "Head Covers": [
      "Disposable Bouffant Cap",
      "PP Head Cover White",
      "Mallmoon Hair Net Cap",
      "Karam Head Cover",
      "Neosafe Bouffant Cap",
    ],
    Aprons: [
      "Disposable PP Apron",
      "LDPE Disposable Apron",
      "Mallmoon Safety Apron",
      "Karam Disposable Apron",
      "Neosafe PP Apron",
    ],
    Coveralls: [
      "Disposable Coverall CC-01",
      "PP Coverall White Pack",
      "Mallmoon Protective Coverall",
      "Karam Disposable Coverall",
      "Neosafe Coverall Suit",
    ],
  },
  "cat-face-ear": {
    "Safety Goggles": [
      "Clear Safety Goggles SG-01",
      "3M SecureFit Goggles",
      "Karam Safety Goggles",
      "Mallmoon Chemical Goggles",
      "Uvex Safety Goggles",
    ],
    "Face Shields": [
      "Polycarbonate Face Shield",
      "3M Face Shield",
      "Karam Face Shield FS-01",
      "Mallmoon Visor Shield",
      "Neosafe Face Shield",
    ],
    "Ear Muffs": [
      "Industrial Ear Muffs EM-01",
      "3M Peltor Ear Muffs",
      "Karam Ear Defender",
      "Mallmoon Ear Muffs",
      "Honeywell Ear Muffs",
    ],
    "Ear Plugs": [
      "Foam Ear Plugs EP-01",
      "3M Ear Plugs 1110",
      "Karam Ear Plugs",
      "Mallmoon Disposable Ear Plugs",
      "Moldex Ear Plugs",
    ],
    Respirators: [
      "Half Face Respirator RF-01",
      "3M Respirator Mask 6200",
      "Karam Safety Respirator",
      "Mallmoon Dust Respirator",
      "Honeywell Respirator",
    ],
  },
  "cat-road-safety": {
    "Traffic Cones": [
      "750mm Traffic Cone",
      "Reflective Traffic Cone 1m",
      "Mallmoon PVC Traffic Cone",
      "Karam Road Cone",
      "Neosafe Traffic Cone",
    ],
    "Warning Tapes": [
      "Red White Warning Tape",
      "Caution Barrier Tape",
      "Mallmoon Reflective Tape",
      "3M Safety Warning Tape",
      "Karam Hazard Tape",
    ],
    Barricades: [
      "Expandable Safety Barricade",
      "Plastic Road Barricade",
      "Mallmoon Safety Barrier",
      "Karam Road Barricade",
      "Neosafe Barricade",
    ],
    "Reflective Strips": [
      "Reflective Sticker Roll",
      "3M Reflective Tape Strip",
      "Mallmoon Retro Reflective Strip",
      "Karam Reflective Band",
      "Neosafe Reflective Strip",
    ],
    "Road Signs": [
      "Caution Road Sign RS-01",
      "Reflective Speed Limit Sign",
      "Mallmoon Warning Road Sign",
      "Karam Traffic Sign Board",
      "Neosafe Road Safety Sign",
    ],
  },
};

export function getDropdownItemsForSection(categoryId: string, section: string): string[] {
  const items = CATEGORY_DROPDOWN_ITEMS[categoryId]?.[section];
  if (items?.length) return items;

  return [
    `${section} Standard Model`,
    `${section} Pro Series`,
    `${section} Industrial Pack`,
    `${section} Heavy Duty Unit`,
    `${section} Economy Line`,
  ];
}
